version: "3"
name: dtp-backend
services:
  search:
    image: typesense/typesense:0.22.2
    volumes:
      - search:/app/data
    # network_mode: host
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_LISTEN_ADDRESS: 127.0.0.1
      TYPESENSE_PEERING_ADDRESS: 127.0.0.1
      TYPESENSE_DATA_DIR: /app/data
      TYPESENSE_API_KEY: test-api-key
      TYPESENSE_ENABLE_CORS: "true"

  firebase:
    image: andreysenov/firebase-tools:latest-node-16
    command: yarn firebase --project demo-dtp emulators:start --only auth,functions,pubsub,firestore,storage --import tests/integration/exportedTestData
    working_dir: /app
    volumes:
      - ..:/app
    # network_mode: host
    ports:
      - "3010:3010"
      - "4400:4400"
      - "9099:9099"
      - "5001:5001"
      - "8080:8080"
      - "8085:8085"
      - "9199:9199"
  builder:
    image: node:16-alpine
    command: yarn --cwd functions build:watch
    working_dir: /app
    volumes:
      - ..:/app
  next:
    image: node:16-alpine
    command: yarn dev
    working_dir: /app
    network_mode: host
    volumes:
      - ..:/app
    environment:
      NEXT_PUBLIC_TYPESENSE_SEARCH_API_KEY: test-api-key
      NEXT_PUBLIC_TYPESENSE_API_URL: http://localhost:8108
      NEXT_PUBLIC_USE_EMULATOR: "true"
      NEXT_PUBLIC_PROJECT_ID_FOR_TEST: demo-dtp

volumes:
  search: {}
